---
title: "nls - sin"
output: html_notebook
---

# a and b estimation

```{r}
source("../../R/2_tusk/utils/simulation.R")
source("../../R/2_tusk/utils/SAEM.R")
```

```{r}
a <- 1
x <- seq(0, 3 * pi, length.out = 100 / a) / a
Y <- A * sin(g(x, rep(0, length(x)), a) + b) + B * sin(2 * (g(x, rep(0, length(x)), a) + b) + pi / 2)

b.est <- init.b(Y, a)
Y.est <- A * sin(g(x, rep(0, length(x)), a) + b.est) + B * sin(2 * (g(x, rep(0, length(x)), a) + b.est) + pi / 2)
```

```{r}
plot(x, Y, type = "l")
lines(x, Y.est, type = "l", col = "red", lty = 2)
abline(h = 0)
abline(v = find.x0(Y))
```

```{r}
a <- .1
b <- 1
x <- seq(0, 3 * pi, length.out = 100 / a) / a
Y <- A * sin(g(x, rep(0, length(x)), a) + b) + B * sin(2 * (g(x, rep(0, length(x)), a) + b) + pi / 2)

b.est <- init.b(Y, a)
Y.est <- A * sin(g(x, rep(0, length(x)), a) + b.est) + B * sin(2 * (g(x, rep(0, length(x)), a) + b.est) + pi / 2)
```

```{r}
plot(x, Y, type = "l")
lines(x, Y.est, type = "l", col = "red", lty = 2)
abline(h = 0)
abline(v = find.x0(Y))
```

```{r}
source("../../R/2_tusk/utils/simulation.R")
```

```{r}
xi <- rxi()
Y <- f(x, xi) + rnorm(n, 0, omega)
```

```{r}
A.B.max <- max(abs(Y)) + omega
A.c <- runif(1, -A.B.max, A.B.max)
B.c <- runif(1, -A.B.max, A.B.max)

ssp <- spectrum(Y)
a.est <- 2 * pi * ssp$freq[[which.max(ssp$spec)]]
a.c <- a.est

b.est <- init.b(Y, a.est)
b.c <- b.est

# less flexible
phi.nls <- nls(y ~ cbind(A = sin(x * a + xi + b), B = sin(2 * (x * a + xi + b) + pi / 2)),
               data = data.frame(y = Y, x = x, xi = xi),
               start = list(a = a.c, b = b.c),
               algorithm = "plinear",
               control = nls.control(warnOnly = TRUE))
coef(phi.nls)

f.min <- function(A, B, a, b) {
  return(f(x, xi, A.arg = A, B.arg = B, a.arg = a, b.arg = b))
}
phi.nls <- nls(Y ~ f.min(A, B, a, b),
               start = list(A = A.c, B = B.c, a = a.c, b = b.c),
               control = nls.control(warnOnly = TRUE))
c <- coef(phi.nls)
print(c)

A.c <- c[[1]]
B.c <- c[[2]]
a.c <- c[[3]]
b.c <- c[[4]]

plot(Y, type = "l")
lines(f(x, xi, A.arg = A.c, B.arg = B.c, a.arg = a.c, b.arg = b.c),
      type = "l", col = "red")
```

```{r}
A.B.max <- max(abs(Y)) + omega
A.c <- runif(1, -A.B.max, A.B.max)
B.c <- runif(1, -A.B.max, A.B.max)

ssp <- spectrum(Y)
a.est <- 2 * pi * ssp$freq[[which.max(ssp$spec)]]
a.c <- a.est

b.est <- init.b(Y, a.est)
b.c <- b.est

f.min <- function(par) {
  return(sum((Y - f(x, xi, A.arg = par[[1]], B.arg = par[[2]],
                     a.arg = par[[3]], b.arg = par[[4]]))^2))
}
# not stable
phi.optim <- optim(par = list(A = A.c, B = B.c, a = a.c, b = b.c),
                   fn = f.min, method = "L-BFGS-B")
c <- phi.optim$par
print(c)

A.c <- c[[1]]
B.c <- c[[2]]
a.c <- c[[3]]
b.c <- c[[4]]

plot(Y, type = "l")
lines(f(x, xi, A.arg = A.c, B.arg = B.c, a.arg = a.c, b.arg = b.c),
      type = "l", col = "red")
```
